### ISSUE TITLE
关于PCA白化的问题

### ISSUE THREAD

**Issue by scnuhealthy** [XJhaoren/PWA#6]
您好，我有个问题。我看你的代码是用oxford数据集训练PCA白化的参数，然后再用这些参数去处理paris数据集(之后的特征操作和检索都与oxford无关了)。我尝试换成用paris数据集训练PCA白化参数，MAP会大大下降。为何要用另一个数据集去训练PCA白化，又为什么这样做可以提高MAP？

**Comment by XJhaoren** [comment]
您好，这个问题确实存在，在ICCV2015 SPOC文章分析说是过拟合问题。PCA效果比较依赖数据集，我们的另一个work IME 基于无监督的流行降维，效果更稳定一些。一些研究使用end-to-end的训练提升网络性能，加入一个全连接层去取代无监督的PCA，并且可以使用一些有监督的后处理方式提升性能（ECCV2016的两篇文章）。
Cnn image retrieval learns from bow: Unsupervised fine-tuning with hard examples
Deep image retrieval: Learning global representations for image search
这两篇分别扩了
PAMI Fine-tuning CNN Image Retrieval with No Human Annotation
IJCV End-to-end learning of deep visual representations for image retrieval

**Comment by scnuhealthy** [comment]
明白了。感谢你的回答
